
default: &default
  adapter: postgresql
  encoding: unicode
  username: satoshy
  password: qwerty
  pool: 5
  host: localhost

development:
  <<: *default
  database: rails_paypal__development

test:
  <<: *default
  database: rails_paypal_test

production:
  <<: *default
  database: db/production.sqlite3
